### PR TITLE
Increase timeout 

### PR DESCRIPTION
**Pull request by zag2me**
So we can go past the 30 second limit on initial sync

### CODE REVIEW

**Comment by da-anda** [comment]
sorry, not gonna happen because this will override Kodi server settings. You can add this config to your developmentConfiguration.php or change your local php.ini

**Comment by zag2me** [comment]
Yep understood. Added it to my private config and works great.

**Comment by da-anda** [comment]
I just realized my wording might have  come over a bit harsh - sorry for that, not intended

**Comment by zag2me** [comment]
No worries at all, you should know me by now. This was more of a git test.

Lots more to come in the future now Garbear taught me all the GIT-foo at devcon!

**Comment by da-anda** [comment]
so now that you're a git wiz you can be blamed hard if you fuckup git ;)

**Pull request closed without merging**
