### PR TITLE
[Task] Update YouTube channel link

### PR DESCRIPTION
**Pull request by zag2me**
Update the YouTube channel link

### CODE REVIEW

**Comment by zag2me** [comment]
Ping @da-anda

**Comment by Razzeee** [comment]
MySpace icon? Oo

**Comment by zag2me** [comment]
Yeh very old theme, icon was re-used ;)

**Comment by Razzeee** [comment]
Aren't these filenames also interpret by search engines?

**Comment by da-anda** [comment]
CSS classes usually not. But exactly these kind of hacks are why I don't like third party themes. You either hack stuff and keep the upgrade compatibility, or you alter the theme and loose it. None of that is an issue if you create your own stuff :)

**Pull request merged**
